name: Create branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo Inputs
        run: |
          echo ${{toJSON(inputs.branch_name)}}
