name: Run Action

on:
  push:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./ext/devops-sandbox-rusefi/.github/workflows/custom-board-build
