name: Update rusEFI Reference

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rusefi/devops-sandbox-rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@master
    permissions:
      contents: write
